export const MenuCategory = [
    {
      id: 1,
      name: "Cupcake",
      item: "22 Items",
      image: "/icon/icon2.png",
      color: "#F0FEEB",
    },
    {
      id: 2,
      name: "Pizza",
      item: "25 Items",
      image: "/icon/icon4.png",
      color: "#E6F3F5",
    },
    {
      id: 3,
      name: "Kebab",
      item: "12 Items",
      image: "/icon/icon3.png",
      color: "#EAEEFA",
    },
    {
      id: 4,
      name: "Salmon",
      item: "22 Items",
      image: "/icon/icon5.png",
      color: "#F9EEF3",
    },
    {
      id: 5,
      name: "Doughnut",
      item: "11 Items",
      image: "/icon/icon1.png",
      color: "#F3F7D9",
    },
    {
      id: 6,
      name: "Cupcake",
      item: "22 Items",
      image: "/icon/icon2.png",
      color: "#F0FEEB",
    },
    {
      id: 7,
      name: "Pizza",
      item: "25 Items",
      image: "/icon/icon4.png",
      color: "#E6F3F5",
    },
    {
      id: 8,
      name: "Kebab",
      item: "12 Items",
      image: "/icon/icon3.png",
      color: "#EAEEFA",
    },
    {
      id: 9,
      name: "Salmon",
      item: "22 Items",
      image: "/icon/icon5.png",
      color: "#F9EEF3",
    },
    {
      id: 10,
      name: "Doughnut",
      item: "11 Items",
      image: "/icon/icon1.png",
      color: "#F3F7D9",
    },
  ];